name: build-release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:

  jira-frontend-app-build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install, Build
        env:
          CI: ""
        run: |
          cd frontend
          npm install
          CI= npm run build
          rm -rf node_modules/gh-pages/.cache
      - name: Deploy
        if: startsWith(github.ref, 'refs/tags/v')
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: frontend/build
          CLEAN: true